language: python
branches:
  only:
  - master
python:
- '3.6'
addons:
  apt_packages:
    - pandoc
    - texlive-latex-base
    - latexmk
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-full
install:
- pip install -U pip
- pip install -r requirements.txt
before_script:
#
script:
- bash run.sh
after_success:
  #test the docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: sphinx/build/html
  on:
    branch: master
  notifications:
    email:
      recipients:
        - nobody@localhost
      on_success: never
      on_failure: always

